### PR TITLE
Added back in depdency

### PR DESCRIPTION
**Pull request by benjaminsage**

### CODE REVIEW

**Review by MojtabaHs — CHANGES_REQUESTED** [review]
Thanks for the PR but there are some issues yet:

1. The color extension is not working always, for example for system colors, asset colors, named colors and etc. So it can't be extended just like that.

2. Why did you changed the custom modifiers' signature? The benefit of being exact same as the original is that there will be no requirements for renaming them as they move up and down in the code and Xcode can automatically detect them. And. another one is that suppresses the nonfunctional modifier as well. 

3. Why did you merge all modifiers in a single file?

4. AccentColor is environmental and it is working as it is desired. No need for explicit implementation.

5. What is the reason for this application: `autofillPrefix = showFlag`?

6. What is the reason for those `if let` expressions in the `updateUIVIew` function? Where is the `else` condition? Also, some of them actually accept `nil` as the correct value (like colors).

7. Line 223 and 224 should switch with each other.

8. Why are you returning `false` for should clear?

9. Isn't there any need for `shouldReturn` as well?

**Comment by benjaminsage** [comment]
Hey,

1. Oh, I didn't know that. I thought you could do a memory dump so long as you have a `Color` object initialized.

2. What do you mean about custom modifier's signature? Like the names of the modifiers? I tried to keep them the same as the native SwiftUI modifiers like `foregroundColor(_:)` and `multilineTextAlignment(_:)`. Where there any modifiers that were different?

On a couple of modifiers, like `onReturn(perform:)`, there is no SwiftUI modifier yet, so they just had to be named what you would think Apple would name them.

3. I just thought it was easier to document and see everything when it was in one file! And it isn't too long of a file yet. I don't know what Apple does. If you don't like it though I don't mind haha.

4. Does `.accentColor(_:)` work to change the cursor color even though it's a `UIViewRepresentable` and not a `View`?

5. I think this is a typo actually. I can't remember. 😌

6. Oops, I think that was by accident. I will fix.

7. Ah.

8. `onClear(_:)` returns a `Bool`, but I wasn't sure what it was. Do you know how I could figure it out?

9. shouldReturn only gets called when the user exits the text field by tapping the return key. They could also exit by, say, tapping another text field. So maybe the programmer would want to be able to detect this difference. 😀

**Review by MojtabaHs — CHANGES_REQUESTED** [review]
Thanks for the changes. Some issues are remaining:

1. 🛑 The Color extension and the issues we discussed.
2. ⚠️ I meant `fontFromUIFont(:)`, why it's not `font(:)` ! By the way, I couldn't find `onReturn(perform:)` 🤔
3. hmmm. I see.
4. 🛑 Yes it is. you can see it in the preview gif. You should completely get rid of that.
5. 🛑 I see no benefits in that. Please double-check and remove it if it's true.
6. ✅ Thanks 👌
7. ✅ 😅
8. 🛑 I was talking about the `shouldClear` method itself. Setting it to false prevents it from clearing. (Imagine the delete button on the keyboard)
9. ⚠️ `shouldReturn` gets called when when 'return' key pressed. You can detect the other situation with `onEndEditing `.

Please fix 🛑s and change or suppress ⚠️s and thanks for ✅s ;)

**Comment by benjaminsage** [comment]
OK! \

1. You're right! Fixed all these.
2. Decided to go with `font(_:)` for now! We can change if people are getting confused. 
3. 😀
4. I completely got rid of it. Would love to know how it works without this.
5. It was misplaced. I made a new modifier to fix this.
6. 🙂
7. 😬
8. I changed this to `true`.
9. You're right. I just added it.

**Review by MojtabaHs — APPROVED** [review]

**Pull request merged**
